Train-Adventure-Endless-Challenge/Train-Adventure

Assets/Settings/URP-HighFidelity.asset
ProjectSettings/GraphicsSettings.asset

- 유니티의 URP 세팅이 빠져 있어 다시 설정
- Asset -> Setting -> URP-HighFidelity -> Rendering List 재 설정

:sparkles:ㅣURP 세팅 살리기 완료

---

Assets/Scripts/Shake/IncreaseShake.cs

:sparkles: | 흔들림 초기화, 감소 함수화

---

Assets/PolygonNatureBiomes/URP_ExtractMe_Nature_Biomes.unitypackage.meta
Assets/Scripts/GearSystem/GearSystem.cs
Assets/Scripts/Item/Item.cs
Assets/Scripts/Item/ItemData.cs
Assets/Scripts/Item/Weapon.cs
ProjectSettings/BurstAotSettings_Android.json

- 내구도 추가
- 장비 분해/파괴 추가
- ItemData에 최대 내구도 변수 추가
- 공격/스킬에서 내구도 감소
- 분해/파괴 시 기획에 맞게 기어를 얻음
- 아직 분해/파괴 시 아이템이 사라지지않음. 
=> 인벤토리에서 item을 넘겨주면 삭제 시키는 로직 필요
=> 플레이어에서 장착된 아이템을 부시는 로직 필요

Feature 내구도, 장비 분해/파괴

---

Assets/Scripts/InteractionObjects/ShakeMachine.cs
Assets/Scripts/InteractionObjects/Test.mat
Assets/Scripts/Shake/IncreaseShake.cs
Assets/Scripts/Shake/ShakeManager.cs

-ShakeMachine에 흔들림 초기화 로직 추가
- ShakeMachine의 로직 중간에 흔들림 초기화 로직을 추가함.
- ShakeManager의 singleton이 TrainManager로 되어 있어 ShakeManager로 수정
- IncreaseShake클래스의 ClearShake 함수에 접근할 수 없어 ShakeManger에 ClearShake함수로 한 번더 감싸 접근 가능하게 변경

Feature 흔들림 오브젝트 보완

---

Assets/Animations/Walk.fbx.meta
Assets/Scenes/TempPlayerScene.unity
Assets/Scripts/Player/Player.cs
Assets/Scripts/Player/PlayerAttack.cs
Assets/Scripts/Player/PlayerData.cs
Assets/Scripts/Player/PlayerManager.cs
Assets/Scripts/Player/PlayerRolling.cs
Assets/Scripts/Player/PlayerStamina.cs
Assets/Scripts/Player/PlayerStamina.cs.meta
Assets/Scripts/Shake/Shake.cs
Assets/Scripts/UI/StaminaSlider.cs
Assets/Scripts/UI/StaminaSlider.cs.meta

- 플레이어 스태미나
- 공격, 구르기시 소모되는 플레이어의 스태미나 추가
- 기획서를 참고하여 최대 스태미나는 100으로 0.5초 동안 변화가 없다면 초 당 20의 양을 회복으로 개발
- Temp 씬에서 사용 및 볼 수 있도록 UI 추가

Feature player stamina

---

Assets/Animations/Walk.fbx.meta
Assets/Materials/Door/Materials/Floor_Mat.mat
Assets/Materials/fdsf.mat
Assets/Prefabs/Player/Player.prefab
Assets/Scenes/TempPlayerScene.unity
Assets/Scripts/Player/Player.cs
Assets/Scripts/Player/PlayerAttack.cs
Assets/Scripts/Player/PlayerData.cs
Assets/Scripts/Player/PlayerInteraction.cs
Assets/Scripts/Player/PlayerManager.cs
Assets/Scripts/Player/PlayerRolling.cs
Assets/Scripts/Player/PlayerStamina.cs
Assets/Scripts/Player/PlayerStamina.cs.meta
Assets/Scripts/Shake/Shake.cs
Assets/Scripts/UI/StaminaSlider.cs
Assets/Scripts/UI/StaminaSlider.cs.meta
ProjectSettings/TagManager.asset

- 플레이어 상호작용
- 상호작용 객체가 범위 안에 들어오면, 키 입력 시 상호작용이 시작되게끔 하였음

Feature interaction

---

Assets/PolygonNatureBiomes/URP_ExtractMe_Nature_Biomes.unitypackage.meta
Assets/Prefabs/Player/Player.prefab
Assets/Scripts/InteractionObjects/Test.mat

- 플레이어의 단검 복구
- 플레이어의 단검이 사라져 있길래 다시 복구 함
- 복구 전 
- 복구 후

🐛 | 단검 모델 복구

---

Assets/Animations/Enemy/Melee/Enemy_Melee.controller
Assets/PolygonNatureBiomes/URP_ExtractMe_Nature_Biomes.unitypackage.meta
Assets/Prefabs/Enemy/TempEnemy_Range.prefab
Assets/Scripts/Enemy/AttackRange/EnemyFieldOfView.cs

- 몬스터의 애니메이션 및 몇몇 로직 수정 
- 기본 몬스터의 Walking 애니메이션 속도 변경 (0.5 -> 1)
- 원거리 몬스터의 공격 범위 축소 
- 몬스터의 플레이어 파싱 방법 FindTag에서 싱글톤으로 변경
- 추후 공격 범위 지정된 데이터로 변경 로직 필요

Feature enemy anim

---

Assets/Animations/Enemy/Melee/Enemy_Melee.controller
Assets/Animations/Enemy/Range/Enemy_Range@AttackWalk.fbx.meta
Assets/Animations/Enemy/Range/Enemy_Range@Idle.fbx.meta
Assets/Animations/Enemy/Range/Enemy_Range@Walking.fbx.meta
Assets/Prefabs/Enemy/HPCanvas.prefab
Assets/Prefabs/Enemy/HPCanvas.prefab.meta
Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Prefabs/Enemy/TempEnemy_Range.prefab
Assets/Scenes/Enemy/EnemyTestMineScene.unity
Assets/Scenes/Enemy/EnemyTestMineScene.unity.meta
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/EnemyDieState.cs
Assets/Scripts/Enemy/State/EnemyIdleState.cs
Assets/Scripts/Enemy/UI.meta
Assets/Scripts/Enemy/UI/EnemyUI.cs
Assets/Scripts/Enemy/UI/EnemyUI.cs.meta

- Enemy HP Bar
- 몬스터의 머리 위에 현재 체력을 나타낼 수 있는 UI 를 Slider를 사용하여 작업하였습니다.

Feature enemy hp bar

---

Assets/Prefabs/Train/NomalTrain/NomalTrain_1.prefab

- 부서지는 벽의 코드가 빠져 있어 추가
- UnbreakableWall의 객체에 Wood Script 추가

:sparkles: | 부서지는 벽에 코드 추가

---

Assets/Prefabs/Item/Weapon/GreatSword.prefab
Assets/Prefabs/Item/Weapon/TempKnife.prefab
Assets/Scripts/Item/Weapon/Dagger.cs
Assets/Scripts/Item/Weapon/GreatSword.cs
Assets/Scripts/Player/Player.cs

- 코드 단순화를 위해 Player가 Entity를 상속 받도록 함
- Player가 Entity를 상속 받도록 함
- 피격 처리를 Entity를 사용하여 처리
- 무기들의 피격 감지 레이어가 장애물(Obstruct)가 추가됨
- 각 무기들의 피격 처리 관련 코드가 EnemyController에서 Entity로 변경

Feature player entity inheritance

---

Assets/Data/Player.asset
Assets/Scripts/Player/Player.cs
Assets/Scripts/Player/PlayerAttack.cs
Assets/Scripts/Player/PlayerController.cs
Assets/Scripts/Player/PlayerData.cs
Assets/Scripts/Player/PlayerDie.cs
Assets/Scripts/Player/PlayerHit.cs
Assets/Scripts/Player/PlayerInteraction.cs
Assets/Scripts/Player/PlayerRolling.cs
Assets/Scripts/Player/PlayerStamina.cs

- 코드를 다시 보니 가독성이 떨어진거 같아 수정
- 각 로직의 상세 설명 추가
- 부분별로 Region으로 나눔
- Data에 빠진 Data 추가

Feature player code refactoring

---

Assets/Scenes/TrainScene/MineScene.unity
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/EnemyDieState.cs

- enemy entity 추가
- enemycontroller에 entity 상속 
- camera에 camera manager cs 추가 
- hit와 die 함수를 controller에서 호출

Hotfix enemy entity

---

Assets/Data/Item/Weapon/DaggerData.asset
Assets/Data/Item/Weapon/GreatSwordData.asset
Assets/Data/Player.asset
Assets/Prefabs/Player/Player.prefab
Assets/Scenes/TrainScene/MineScene.unity
Assets/Scripts/Player/Player.cs
Assets/Scripts/Player/PlayerAttack.cs
Assets/Scripts/Player/PlayerController.cs
Assets/Scripts/Player/PlayerInteraction.cs
Assets/Scripts/Player/PlayerRolling.cs

- 플레이어 초기화 오류 수정
- 플레이어, 무기 공격 속도 수정
- 코루틴 종료 일부 삭제

:bug: 플레이어 초기화 오류 수정

---

Assets/Animations/Enemy/Range/Enemy_Range@Attack.fbx.meta
Assets/Materials/Train/mWood_4.mat
Assets/Materials/Train/mWood_7.mat
Assets/Scenes/TrainScene/MineScene.unity
Assets/Scripts/Enemy/EnemyBullet.cs
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/EnemyDieState.cs
Assets/Scripts/Enemy/Type/EnemyController_Range.cs

- 원거리 몬스터의 공격 anim , 로직 변경 
- 원거리 몬스터의 공격 모션이 너무 우스꽝 스럽고 선 딜레이가 길어 게임에 맞지 않다고 판단
- 총을 쏘는 듯한 모션으로 변경
- animation clip event로 총알 생성

Feature enemy range attack

---

Assets/Materials/fdsf.mat
Assets/Prefabs/Train/NomalTrain/NomalTrain.prefab
Assets/Prefabs/Train/NomalTrain/TrainObject.prefab
Assets/Scenes/TrainSystemScene.unity
Assets/Scenes/TrainSystemScene.unity.meta
Assets/Scripts/ObjectInTrain/Test/TestMaterial.mat
Assets/Scripts/ObjectInTrain/Test/WarningObject.mat
Assets/Scripts/Train/NomalTrain.cs

- 기차 문 추가 
- 문 asset 추가 
- 기차 문 배치

Feature train system

---

Assets/Animations/Enemy/Melee/Enemy_Melee.controller
Assets/Animations/Enemy/Melee/Enemy_Melee@Attack.fbx.meta
Assets/Animations/Enemy/Melee/Enemy_Melee@AttackWalking.fbx.meta
Assets/Animations/Enemy/Melee/Enemy_Melee@Hit.fbx.meta
Assets/Animations/Enemy/Melee/Enemy_Melee@Idle.fbx.meta
Assets/Animations/Enemy/Melee/Enemy_Melee@Walking.fbx.meta
Assets/Animations/Enemy/Melee/Enemy_Melee_Die.fbx.meta
Assets/Animations/Enemy/Range/Enemy_Range@Die.fbx.meta
Assets/Data/Enemy/Temp_Enemy_Melee.asset
Assets/Materials/Train/mWood_4.mat
Assets/Materials/Train/mWood_7.mat
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/EnemyAttackWalkState.cs
Assets/Scripts/Enemy/State/EnemyDieState.cs
Assets/Scripts/Enemy/State/EnemyMoveState.cs
Assets/Scripts/Enemy/Type/EnemyController_Melee.cs
Assets/Scripts/Enemy/Type/EnemyController_Range.cs

- Enemy Dead 
- 몬스터 죽음 처리
- Enemy clip event 로 실행

:bug: ㅣ EnemyDead

---

Assets/Animations/Die.fbx.meta
Assets/Scripts/Player/PlayerDie.cs

- 플레이어 죽음 버그 수정
- 플레이어 죽음시 공격 판정을 그대로 받아와 계속 죽음이 실행되는 버그 발생
- 플레이어 죽음시 애니메이션 자체 y 값이 고정되어 바닥에서 떠서 죽는 버그 발생
- PlayerDie에 _isDie bool 변수 추가
- Die 함수에 _isDie가 true이면 실행 그만둠
- 플레이어 죽음 애니메이션 y값 포즈에 따라 다르게 처리

Hotfix player die

---

Assets/Scripts/Player/PlayerController.cs

- 플레이어가 공격시 방향 전환이 안되게 수정
변경 전
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/d9c8b790-2247-4278-b992-159569f93132
변경 후
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/2d036912-8ee8-44f6-96e5-7ad0b3de2650
-  if (_player.playerState != PlayerState.Attack) _moveDirection = new Vector3(x, 0f, z).normalized; // 움직임 방향 으로 수정

:art: | 플레이어가 공격시 방향 전환이 안되게 수정

---

Assets/Prefabs/Enemy/TempBullet.prefab
Assets/Scripts/Enemy/EnemyBullet.cs

- 원거리 총알 공격 로직 수정 
- onwer의 방향을 받아와서 일직선으로 발사

:bug: ㅣ 원거리 공격 로직 수정

---

Assets/Scripts/GearSystem/GearSystem.cs
Assets/Scripts/Item/Item.cs

- 주석 추가
- 설명이 필요해보이는 아이템 분해 쪽 주석 추가

Hotfix add annotation

---

Assets/Data/Item/Weapon/DaggerData.asset
Assets/Data/Item/Weapon/GreatSwordData.asset
Assets/Prefabs/Effect.meta
Assets/Prefabs/Effect/Attack Impact 2.prefab
Assets/Prefabs/Effect/Attack Impact 2.prefab.meta
Assets/Prefabs/Effect/Attack Impact.prefab
Assets/Prefabs/Effect/Attack Impact.prefab.meta
Assets/Prefabs/Enemy/HPCanvas.prefab
Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Prefabs/Enemy/TempEnemy_Range.prefab
Assets/Prefabs/Player/Player.prefab
Assets/Scenes/TrainScene/MineScene.unity
Assets/Scripts/Item/ItemData.cs
Assets/Scripts/Item/Weapon/Dagger.cs
Assets/Scripts/Item/Weapon/GreatSword.cs
Assets/Scripts/Item/Weapon/Weapon.cs

- 플레이어 타격감 추가
- 에셋 추가하여 타격감 추가

:sparkles: | 플레이어 타격감 추가

---

Assets/Prefabs/Enemy/HPCanvas.prefab
Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Prefabs/Enemy/TempEnemy_Range.prefab
Assets/Prefabs/Enemy/TempEnemy_Scientist.prefab

- 테스트 후 몬스터의 기본적인 로직 수정
- 몬스터 시야각 180 -> 360
- 몬스터 HP UI 에러 해결

Feature enemy 

---

Assets/Prefabs/Train/UpgadeNomalTrain_1.prefab
Assets/Scenes/TrainUpgradeScene.unity
Assets/Scripts/ObjectInTrain/Test/TestMaterial.mat

- 기차 수정
- 기차 크기 수정
- 기차 내 파이프 콜라이더 적용

Feature-기차 수정

---

Assets/Scripts/Player/PlayerManager.cs

- 스테미나 시스템 수정
- 원래 Idle일때 일정 시간 이후 재생
- 변경 후 스테미나를 사용하지않을 경우 일정 시간 이후 재생

:art: | 스테미나 시스템 수정

---

Assets/Animations/Enemy/Melee/Enemy_Melee.controller
Assets/Animations/Enemy/Melee/Enemy_Melee@Attack.fbx.meta
Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Scripts/Enemy/EnemyAttack_Melee.cs
Assets/Scripts/Enemy/State/EnemyAttackState.cs
Assets/Scripts/Enemy/Type/EnemyController_Melee.cs

- enemy anim 속도 변경
- 기존 enemy 움직임에 비해 animation 속도가 느려 어색했다. 
- animation의 speed를 증가시켰다.
- walk speed : 1 -> 1.5로 변경
- walking_target : 1 -> 2로 변경

:art: ㅣ enemy walk speed update

---

Assets/Prefabs/SpawnPoint.meta
Assets/Prefabs/SpawnPoint/TestSpawnpointObject.prefab
Assets/Prefabs/SpawnPoint/TestSpawnpointObject.prefab.meta
Assets/Prefabs/Train/UpgadeNomalTrain_1.prefab
Assets/Scenes/TrainUpgradeScene.unity
Assets/Scripts/Train/NomalTrain.cs
Assets/Scripts/Train/SpawnPointSystem.cs
Assets/Scripts/Train/SpawnPointSystem.cs.meta

- spawnpoint system 추가
- 현재는 기차와 spawnpoint가 함께 프리팹화 되고있는 걸 변경함
- 기차 프리팹은 하나지만 그  안에서 spawnpoint와 오브젝트들의 프리팹을 소환하도록 변경ㅇ

Feature spawnpoint prefab system

---

Assets/Animations/UI.meta
Assets/Animations/UI/GameOverPanel.controller
Assets/Animations/UI/GameOverPanel.controller.meta
Assets/Animations/UI/GameOverPanel_Start.anim
Assets/Animations/UI/GameOverPanel_Start.anim.meta
Assets/Prefabs/Manager/GameOverManager.prefab
Assets/Prefabs/Manager/GameOverManager.prefab.meta
Assets/Prefabs/UI/GameOverUI.prefab
Assets/Scenes/Test/AttackLogicTestScene 1.unity
Assets/Scenes/Test/AttackLogicTestScene 1.unity.meta
Assets/Scenes/Test/AttackLogicTestScene.unity
Assets/Scripts/GameOver.meta
Assets/Scripts/GameOver/GameOverManager.cs
Assets/Scripts/GameOver/GameOverManager.cs.meta
Assets/Scripts/Player/Player.cs
Assets/Scripts/Player/PlayerHit.cs
Assets/Scripts/Train/InGameManager.cs
Assets/Scripts/UI/GameOverUI.cs
Assets/Scripts/UI/GameOverUI.cs.meta

- GameOver UI
- 게임 종료시 화면 암전 효과
- 중앙 Restart 버튼 클릭시 현재 씬 다시 로드 (재시작)
- 추후 UI 디자인 필요

Feature game over

---

Assets/Resources/Prefabs/Gear.prefab
Assets/Scenes/Test/AttackLogicTestScene 1.unity
Assets/Scripts/InteractionObjects/Gear.cs
Assets/Scripts/InteractionObjects/TreasureBox.cs
Assets/Scripts/ObjectInTrain/Test/WarningObject.mat
ProjectSettings/TagManager.asset

- 보물상자 기어 오류 수정 
- 기어가 플레이어한테 밟혀 플레이어가 공중에 뜨는 에러 수정
- 기존 로직 체크를 trigger로 체크하고, 하위 모델에 collider를 적용
- layer를 통해 모델의 collider 플레이어와 적용 x

:bug: ㅣ gear collider 충돌 with player 해결

---

Assets/Scenes/TestScene/ItemSystemTestScene.unity
Assets/Scripts/Player/PlayerController.cs
Assets/Scripts/Player/PlayerManager.cs
ProjectSettings/TagManager.asset

- 중력 버그 픽스
-  원래 CharacterController의 isGrounded를 사용해 움직일 때가 아니면 중력이 적용되지않음.
- 직접 ray를 쏴 grounded를 체크함.

Feature-중력 버그 수정

---

Assets/Animations/Player/LowPolyHumanAnimator.controller

Hot fix animator structure change

---

Assets/Prefabs/InventorySystem/InventorySystemCanvas.prefab
Assets/Prefabs/UI/DescriptionImage.prefab
Assets/Prefabs/UI/DescriptionImage.prefab.meta
Assets/Scenes/GameCycle.unity
Assets/Scripts/Inventory/DescriptionImage.cs
Assets/Scripts/Inventory/DescriptionImage.cs.meta
Assets/Scripts/Inventory/InventoryItem.cs
Assets/Scripts/Inventory/InventoryManager.cs
Assets/Scripts/Inventory/OnMouseCheckItem.cs
Assets/Scripts/Inventory/OnMouseCheckItem.cs.meta
Assets/Scripts/Item/Item.cs

- 인벤토리 아이템 정보창 보여주기
- 아이템 정보창 프리팹 제작
- 마우스가 인벤토리 아이템 위로 올라갔는지 체크

Feature inventory item info

---

Assets/Scenes/TestScene/GreatSwordSkillTestScene.unity
Assets/Scripts/Inventory/InventoryEquipmentSlot.cs
Assets/Scripts/Inventory/InventorySlot.cs
Assets/Scripts/Player/PlayerEquip.cs

- 무기를 스왑하면 캐릭터가 멈추는 버그 수정
- 무기를 스왑할 시 로직이 의도대로 실행되지않아서 로직을 수정함.
- Take를 하려고할 때( 기존 무기를 지우려고할 때) currentWeapon이 바뀌어 현재 무기가 삭제된 것을 발견함
=> slot의 순서를 바꿔줌

Hot fix weapon swap error

---

Assets/Prefabs/Camera/QuarterViewCam.prefab
Assets/Prefabs/Train/TrainObjectModel.prefab
Assets/Scenes/TestScene/CameraAdjustScene.unity
Assets/Scenes/TestScene/CameraAdjustScene.unity.meta
ProjectSettings/TagManager.asset

- 카메라가 외부로 나가는 것 수정
- 카메라가 외부로 나가려고하면 플레이어가 가까워지도록 제작
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82389915/5a2abf1b-76ba-467c-b994-79a8f74d5c71

Feature camera adjustment

---

Assets/Prefabs/Enemy/HPCanvas.prefab
Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Scenes/GameCycle.unity
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/EnemyHitState.cs
Assets/Scripts/Enemy/UI/EnemyUI.cs
Assets/Scripts/Player/Player.cs
Assets/Scripts/Player/PlayerInteraction.cs
Assets/Scripts/UI/IngameUIController.cs
Assets/Scripts/Util/Entity.cs

- 적 Hp Bar
- 적이 HitState로 바뀌었을 때 Hp Bar 켜기
- Hp Bar 색 변경 (그린 -> 레드)
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80678083/a016cd04-6db7-4419-b79a-d6bda5360019

Feature enemy hp bar on off

---

Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Scripts/Enemy/Type/EnemyController_Melee.cs

- MeleeEnemy의 공격에 Trail 추가
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82389915/2986da70-562a-46da-8b16-0501a006cfe6

Feature enemy attack trail

---

Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Scripts/Enemy/Type/EnemyController_Melee.cs

Reverts Train-Adventure-Endless-Challenge/Train-Adventure#125

Revert "Feature enemy attack trail"

---

Assets/Animations/Player/LowPolyHumanAnimator.controller
Assets/Animations/Player/LowPolyHumanAnimator.controller.meta
Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Prefabs/Player/Player.prefab
Assets/Scenes/GameCycle.unity
Assets/Scripts/Enemy/Type/EnemyController_Melee.cs

- 애니메이터 missing 버그 수정
- enemyAttackTrail을 merge한 이 후 애니메이터가 사라짐
- merge를 revert함
- revert한 내용과 animator missing 버그를 수정하고 다시 pr을 날림

Hotfix animator missing bug

---

Assets/Animations/Player/LowPolyHumanAnimator.controller
Assets/Animations/Player/LowPolyHumanAnimator.controller.meta
Assets/Prefabs/Effect/ItemDestroyEffect.prefab
Assets/Prefabs/Effect/ItemDestroyEffect.prefab.meta
Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Prefabs/Player/Player.prefab
Assets/Prefabs/Train/TrainObjectModel.prefab
Assets/Resources/Prefabs/Item/Dagger.prefab
Assets/Resources/Prefabs/Item/GreatSwrod.prefab
Assets/Resources/ScriptableObjects/Item/DaggerData.asset
Assets/Resources/ScriptableObjects/Item/GreatSwordData.asset
Assets/Scenes/GameCycle.unity
Assets/Scripts/Enemy/Type/EnemyController_Melee.cs
Assets/Scripts/Enemy/UI/EnemyUI.cs
Assets/Scripts/Inventory/InventoryEquipmentSlot.cs
Assets/Scripts/Inventory/InventoryItem.cs
Assets/Scripts/Inventory/InventoryManager.cs
Assets/Scripts/Inventory/InventorySlot.cs
Assets/Scripts/Item/Item.cs
Assets/Scripts/Item/Weapon/Dagger.cs
Assets/Scripts/Item/Weapon/GreatSword.cs
Assets/Scripts/Item/Weapon/Weapon.cs
Assets/Scripts/Player/PlayerEquip.cs
Assets/Scripts/Player/PlayerManager.cs
Assets/Scripts/Player/PlayerSkill.cs

- 아이템 내구도 관련 기능 개발
- 아이템 내구도 데이터를 할당함.
=> 인벤토리에서 수치가 반영안됨
=> 생성한 무기의 아이템 스크립트를 inventory에 할당해 해결
- 아이템 내구도가 0 이하로 내려가면 아이템 파괴
=> 파괴 이펙트 후 아이템이 분리되어 떨어짐.

Feature durability- DestroyItem

---

Assets/Scripts/Item/Item.cs
Assets/Scripts/Item/ItemObject.cs
Assets/Scripts/Item/Weapon/GreatSword.cs
Assets/Scripts/Player/PlayerEquip.cs

- 인벤토리에 아이템을 넣는 로직 수정
- 자잘한 버그 수정
- 아이템을 장착하면 내구도가 초기화되는 버그 수정
=> 아이템을 장착할 때 기존 데이터를 넣어주어 해결함.
- 원래 item에 데이터만 포함한 데이터를 넣었다.
- Item이 아닌 그 아이템의 class타입을 업캐스팅 하여 넣어둠.

Hotfix item object add item logic modify

---

Assets/Scripts/Inventory/InventoryItem.cs
Assets/Scripts/Inventory/InventoryManager.cs
Assets/Scripts/Inventory/InventorySlot.cs
Assets/Scripts/Inventory/OnMouseCheckItem.cs

- 인벤토리 버그 수정 
- 인벤토리를 껐을 때 드래그 아이템이 남는 버그 수정
- 인벤토리를 껐을 때 아이템 설명창이 남는 버그 수정

Feature inventory description bug

---

Assets/Resources/ScriptableObjects/Item/PotionData.asset
Assets/Scripts/Item/ItemObject.cs
Assets/Scripts/Item/Weapon/Dagger.cs

- 아이템 오브젝트 버그 수정
- Id가 0이 들어가서 프리팹이 생성이 되지 않던 버그 수정

:bug: | ItemObjectIdBug

---

Assets/Prefabs/Effect/FistAttackImpact.prefab
Assets/Prefabs/Effect/FistAttackImpact.prefab.meta
Assets/Resources/ScriptableObjects/Item/FistData.asset
Assets/Scripts/Item/Weapon/Fist.cs
Assets/Scripts/Item/Weapon/Weapon.cs

- 주먹 타격 파티클 조정
- trail renderer 활성화 타이밍 조정
- 주먹 타격 파티클을 좀 더 하얗고 작게 변경
- trail renderer가 collider와 함께 animation evnet로 활성화되도록 조정
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82389915/9f1c8db4-6949-40fd-a981-5227585a3adb

Hotfix fist attack adjustment

---

Assets/Prefabs/InventorySystem/InventorySystemCanvas.prefab
Assets/Scripts/Inventory/InventoryItem.cs
Assets/Scripts/Inventory/InventoryManager.cs

- 아이템 내구도 수리
- 기어 20을 소모하여 내구도를 모두 수리한다.
- UI는 임시로 제작함.

Feature item repair

---

Assets/Model/Box/gear_box.fbx.meta
Assets/Model/ObjectInTrain/blence (2).fbx.meta
Assets/Model/ObjectInTrain/gear.fbx.meta
Assets/Prefabs/ObjectInTrain/ShakeMachine.prefab
Assets/Prefabs/ObjectInTrain/ShakeMachine.prefab.meta
Assets/Prefabs/ObjectInTrain/TreasureBox.prefab
Assets/Prefabs/Train/NomalTrain/UpgadeNomalTrain_Model.prefab
Assets/Resources/Prefabs/Gear.prefab
Assets/Scripts/InteractionObjects/TreasureBox.cs
Assets/Scripts/Inventory/InventoryItem.cs
Assets/Scripts/Player/PlayerInteraction.cs

- 기차 오브젝트 아웃라인 버그 수정 
- 오브젝트 모델에서 Read/Write Enabled 체크 해주기
- 오브젝트 프리팹에 Outline script 추가하기

Feature out line bug fix

---

Assets/Scripts/Enemy/Controller/EnemyController_Bomb.cs
Assets/Scripts/Enemy/Controller/EnemyController_Boss_Cave.cs
Assets/Scripts/Enemy/State/Boss/BossEnemyIdleState.cs

- boss 관련 기능 코드리뷰 hotfix
- test용 debug 삭제 
- 기존 vector2 로 distance 체크 로직을 vector 3로 변경

Hotfix boss

---

Assets/Scripts/Enemy/State/EnemyHitState.cs

- 몬스터 Hit Check 오류 해결 
- enemy controller를 get 전에 호출하여 발생하는 오류 해결

:bug: ㅣ Enemy Check Hit

---

Assets/Prefabs/UI/PlayerUI.prefab
Assets/Scenes/StoreTrainTest.unity
Assets/Scripts/UI/IngameUIController.cs

- 흔들림 UI 수정
- 흔들림 UI 배경 추가 
- 스테이지 넘어갈 때 초기화 되는 버그 수정
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80678083/5bae4d03-1d34-4b24-b9a9-b6691e618905

:sparkles: | 흔들림 UI 배경 추가

---

Assets/Prefabs/Player/Hit Volume.prefab
Assets/Prefabs/Player/Hit Volume.prefab.meta
Assets/Scenes/StoreTrainTest.unity
Assets/Scenes/TempPlayerScene/Hit Volume.asset
Assets/Scenes/TestScene/TempPlayerScene.unity
Assets/Scripts/PostProcessing/HitVolume.cs

- 플레이어 Hit Volume 수정
- 플레이어 Hit Volume 수정

🎨 | HitVolume 보완

---

Assets/Animations/Enemy/Range/Attack.anim
Assets/Prefabs/Enemy/TempBullet.prefab
Assets/Prefabs/Player/Hit Volume.prefab
Assets/Prefabs/Player/Hit Volume.prefab.meta
Assets/Scenes/StoreTrainTest.unity
Assets/Scenes/TempPlayerScene/Hit Volume.asset
Assets/Scenes/TestScene/TempPlayerScene.unity
Assets/Scripts/Enemy/Controller/EnemyController_Range.cs
Assets/Scripts/Enemy/Controller/EnemyController_Scientist.cs
Assets/Scripts/Enemy/EnemySpawn/EnemyBullet.cs
Assets/Scripts/PostProcessing/HitVolume.cs
ProjectSettings/DynamicsManager.asset
ProjectSettings/TagManager.asset

- 몬스터 총알 
- trail 추가 
- 총알 이동로직 변경
- trigger 체크에서 collision 체크로 변경 => 벽이나 기차 바닥에 충돌했을 시 밀림을 방지 
- 몬스터와의 충돌에서는 충돌 처리를 하지 않게 layer 설정
- 기존이동이 실제 플레이어를 피격하지 못하였다. 따라서 플레이어 방향으로 rotation을 회전시키고 이동하는 로직으로 수정하였다 
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/81548078/3502f8a8-620d-4ef7-94a9-3ae3f67c7bdd

Feature enemy bullet

---

Assets/Scenes/LoadScene.unity
Assets/Scenes/LoadScene.unity.meta
Assets/Scenes/StartScene.unity
Assets/Scenes/StartScene.unity.meta
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/UI/StartSceneUI.cs
Assets/Scripts/UI/StartSceneUI.cs.meta
Assets/Scripts/Util/LoadSceneController.cs
Assets/Scripts/Util/LoadSceneController.cs.meta
ProjectSettings/EditorBuildSettings.asset

Feature start scene

---

Assets/Scripts/Enemy/Controller/EnemyController_Melee.cs
Assets/Scripts/Enemy/State/EnemyDieState.cs

- Enemy 가 사망 시에 trail을 비활성화 시켰다.
- trail object public으로 보호수준 변경 
- die state에서 trail 비활성화

:art: ㅣ enemy trail 비활성화

---

Assets/Scripts/Enemy/AttackTrans/EnemyAttack_BossCave_Punch.cs
Assets/Scripts/Enemy/Controller/EnemyController_Boss_Cave.cs

- 보스 펀치 공격 effect
- effect의 크기를 키웠다

Hotfix boss fix jump effect

---

Assets/Scenes/TestScene/ItemUpgradeTestScene.unity
Assets/Scripts/Inventory/InventoryEquipmentSlot.cs
Assets/Scripts/Inventory/InventorySlot.cs
Assets/Scripts/Player/PlayerEquip.cs

- 주먹 오브젝트가 Null 값이 되는 오류 수정
- 아이템 슬롯의 실행 순서Take -> Put, 이때 무기를 방어구칸에 넣으려고하면
=> Take: Release하며 주먹으로 currentWeapon 세팅
-> Put: 방어구 슬롯이라 실행안됨(다시 웨폰슬롯으로 들어감) -> 주먹으로 세팅됐지만 웨폰칸에 무기가들어있는 상황발생 
-> 후에 무기를 빼려고하면 주먹 삭제
이 문제를 해결함
- 아이템을 Put할 때 오류가 나면(무기를 방어구 칸에 넣으려고 하면) 다시 아이템을 장착하는 로직을 실행해줌.

:bug: | 주먹이 Null값이 되는 버그 수정

---

Assets/Prefabs/UI/DescriptionImage.prefab
Assets/Scenes/StoreTrainTest.unity
Assets/Scripts/Inventory/DescriptionImage.cs
Assets/Scripts/Inventory/OnMouseCheckItem.cs
Assets/Scripts/Outline/Outline.cs.meta

- 아이템 내구도 게이지 구현
- 아이템 설명창 내구도 부분을 Slider을 사용해서 게이지 구현 
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80678083/1b3af8c9-5d73-43bd-b8e5-e64ae47e9011

🤩 | 아이템 정보 내구도 게이지로 구현

---

Assets/Prefabs/InventorySystem/InventorySystemCanvas.prefab
Assets/Prefabs/InventorySystem/UpgradeUI.prefab

- 인벤토리 UI, 업그레이드 UI 변경
- 인벤토리 UI, 업그레이드 UI 변경

:art: | Inventory UI, Update UI 변경

---

Assets/Animations/Enemy/Scientist/Scientist@Hit.fbx.meta
Assets/Prefabs/Enemy/Effect/EliteEffect.prefab
Assets/Prefabs/Enemy/Effect/EliteEffect.prefab.meta
Assets/Prefabs/Enemy/TempEnemy_Bomb.prefab
Assets/Prefabs/Enemy/TempEnemy_Scientist.prefab

- Elite Enemy
- 미친 과학자 피격시 원 상태로 돌아오지 않는 오류 해결 => Animation clip 종료후 idle로 돌아오는 event가 설정되지 않았음 
- 엘리트 몬스터의 effect 추가

Hotfix scientist

---

Assets/Scripts/Enemy/Controller/EnemyController_Boss_Cave.cs

- Boss 피격 Bug 
- MoveStaet가 할당되지 않아 다른 기능들이 작동하지 않은 것으로 보임

:bug: ㅣ boss state 추가

---

Assets/Model/Item/portion (1).fbx.meta
Assets/Model/ObjectInTrain/blast_furnace.fbx.meta
Assets/Prefabs/Enemy/Boss/Enemy_BossCave.prefab
Assets/Prefabs/InventorySystem/InventorySystemCanvas.prefab
Assets/Prefabs/ObjectInTrain/UpgradeObject.prefab
Assets/Prefabs/Player/Player.prefab
Assets/Prefabs/Train/TutorialTrain.prefab
Assets/Resources/Prefabs/Item/GodGreatSwrod.prefab
Assets/Resources/Prefabs/Item/GodGreatSwrod.prefab.meta
Assets/Resources/ScriptableObjects/Item/GodSwordData.asset
Assets/Resources/ScriptableObjects/Item/GodSwordData.asset.meta
Assets/Scenes/GameCycle.unity

- Game Cycle 제작 
- TutorialTrain ShakeMachine 프리팹으로 변경
- InventorySystem OnMouseCheckItem 스크립트 중복 제거
- GameCycle 보완

Feature game cycle

---

Assets/Prefabs/UI/PlayerUI.prefab
Assets/Scenes/GameCycle.unity
Assets/Scripts/Item/Item.cs
Assets/Scripts/Player/PlayerEquip.cs
Assets/Scripts/UI/IngameUIController.cs

- 인게임 내구도 UI 
- 인게임 내구도 UI 구현
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80678083/5b6ff436-f89f-4e5d-8e93-8ae2fc80a6b2

🤩 | 내구도 UI 구현

---

Assets/Animations/UpgradeObject/Return.anim
Assets/Animations/UpgradeObject/Return.anim.meta
Assets/Animations/UpgradeObject/Upgrade.anim
Assets/Animations/UpgradeObject/UpgradeObject.controller
Assets/Materials/UpgradeObject/gold 1.mat
Assets/Materials/UpgradeObject/gold.001 1.mat
Assets/Prefabs/ObjectInTrain/UpgradeObject.prefab
Assets/Scripts/Item/Item.cs

- 모루 애니메이션 변경
- 모루 애니메이션 변경
- 강화 시 아이템 이름이 강화된 OOO으로 변경됨
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82389915/b573a351-1db0-4d04-bcdd-1e6beecf7bef
마지막에 한번 더 실행되는 오류는 고쳤습니다.(예전 영상)

Fix upgrade object animation

---

Assets/Prefabs/Train/NomalTrain/UpgadeNomalTrain_Model.prefab
Assets/Prefabs/Train/TutorialTrain.prefab
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Inventory/OnMouseCheckItem.cs
Assets/Scripts/Item/Weapon/Dagger.cs
Assets/Scripts/Item/Weapon/GreatSword.cs
Assets/Scripts/Managers/Sound/SoundManager.cs
Assets/Scripts/Player/PlayerSkill.cs

- Sound 머지 후 생긴 버그 수정
- 각 Sound Clip 설정, 호출 버그 수정

Hotfix-Sound

---

Assets/Prefabs/ObjectInTrain/ShakeMachine.prefab
Assets/ShakeMachineInteractionText.cs

:bug: | 균형유지장치 기어 수 업데이트 안되는 버그 수정

---

Assets/Prefabs/UI/PlayerUI.prefab
Assets/Scenes/GameCycle.unity
Assets/Scripts/InteractionObjects/ShakeMachine.cs
Assets/Scripts/InteractionObjects/StoreItemObject.cs
Assets/Scripts/Inventory/InventoryManager.cs
Assets/Scripts/Item/Item.cs
Assets/Scripts/Item/ItemUpgradeSystem.cs
Assets/Scripts/Managers/Gear/GearManager.cs

Feature popup text apply

---

Assets/Scripts/Inventory/InventoryManager.cs
Assets/Sound/Test/EnemyDieSound.wav.meta

:bug: | 내구도 수리시 업데이트안되던 버그 수

---

Assets/Animations/Enemy/Boss/Punch Attack.anim
Assets/Prefabs/Train/BossTrain.prefab
Assets/Prefabs/Train/NomalTrain/UpgadeNomalTrain_Model.prefab
Assets/Prefabs/Train/TrainObjectModel.prefab
Assets/Prefabs/Train/TutorialTrain.prefab
Assets/Resources/ScriptableObjects/Item/GodSwordData.asset
Assets/Scenes/TestScene/BossTestScene.unity
Assets/Scripts/Enemy/AttackTrans/EnemyAttack_BossCave_Punch.cs
Assets/Scripts/Enemy/Controller/EnemyController_Boss_Cave.cs
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/Boss/BossEnemyIdleState.cs
Assets/Scripts/Inventory/OnMouseCheckItem.cs
Assets/Scripts/Item/Weapon/Dagger.cs
Assets/Scripts/Item/Weapon/GreatSword.cs
Assets/Scripts/Managers/Sound/SoundManager.cs
Assets/Scripts/Player/PlayerSkill.cs
ProjectSettings/TagManager.asset

- 보스 에러 
- Boss Train 바닥에 Train tag

Hotfix enemy

---

Assets/Scripts/InteractionObjects/StoreItemObject.cs

상점 아이템 데이터 없는 버그 수정

---

Assets/Scripts/Enemy/State/EnemyHitState.cs

- Enemy Hit 시 trail off
- Hit State로 전환시 trail off

:art: ㅣ enemy 피격시에 trail off

---

Assets/Resources/Prefabs/Item/Dagger.prefab
Assets/Resources/Prefabs/Item/GodGreatSwrod.prefab
Assets/Resources/Prefabs/Item/GreatSwrod.prefab
Assets/Scripts/Enemy/EnemySpawn/EnemyBullet.cs
ProjectSettings/TagManager.asset

-원거리 공격 총알 
- 벽에 충돌 시 삭제 
- weapon layer 추가 => bullet과 collision matrix 설정

:bug: ㅣ 총알 벽 충돌 시 파괴

---

Assets/Scenes/TitleScene.unity
Assets/Scripts/Util/LoadSceneController.cs

- Loading Scene 버그 수정
- Loading Scene이 사용되지 않던 버그 수정
- 영상
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/98545392-eae6-4638-8ab3-f17a79ea0958

Feature-LoadingScene

---

Assets/Prefabs/Train/TrainObjectModel.prefab

- 기차 사이에 플레이어가 떨어지던 버그 수정
- 기차 사잇공간에 콜라이더 추가
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82389915/c9908bc3-ef92-4e2e-9d73-c4a081f8edb3

:bug: | 플레이어 떨어지던 버그 수정

---

Assets/Scripts/Managers/GameFlow/InGameManager.cs
Assets/Scripts/Player/PlayerController.cs
Assets/Scripts/Player/PlayerManager.cs

- 다음 칸 이동 시 캐릭터가 공중에서 허우적 대던 버그 수정
- fade in/out 시 플레이어의 입력을 막고, 애니메이터 파라미터를 세팅해줌.
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82389915/7f720933-de9b-4694-8856-ac9011395e63

Fix next stage player moving error

---

Assets/Scripts/Enemy/State/EnemyHitState.cs

- 엘리트 몬스터 피격시 에러 수정
- Hit State의 근거리 몬스터 예외처리

:lock: ㅣ hit 상태시 근거리 몬스터  공격 trail 예외처리

---

Assets/Scripts/InteractionObjects/Gear.cs
Assets/Scripts/InteractionObjects/TreasureBox.cs
Assets/Scripts/Managers/GameFlow/InGameManager.cs
Assets/Scripts/Managers/Gear/GearManager.cs

- Gear 관련 변경사항들 적용
- 다음 칸으로 넘어갈 시 생성된 기어 오브젝트 삭제
- 상자에서 0.5초 (임시) 이후 기어가 흡수 되게 변경

Hotfix gear

---

Assets/Scripts/UI/GamePauseUI.cs
Assets/Scripts/Util/LoadSceneController.cs

- 타이틀 화면 배경음악 초기화
- 메뉴로 나가기 버튼 누를시 무작전 이동하는 코드 수정
- Title씬 도착시 배경음악 초기화

Hotfix-TitleBackgroundInit

---

.github/workflows/activation.yml

- on push 경로 추가
- CI 에러로 인해서 activation.yml 파일에 on push 경로를 추가하여 실행될 수 있도록 하였습니다.

🔀 :: on push 경로 추가

---

Assets/Animations/Enemy/Melee/Enemy_Melee.controller
Assets/Scenes/GameCycle.unity
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/EnemyDieState.cs
Assets/Scripts/Enemy/State/EnemyHitState.cs
Assets/Scripts/Enemy/State/EnemyIdleState.cs
Assets/Scripts/Item/Weapon/GreatSword.cs

-  Enemy 장검 공격시 죽지 않는 에러 해결 
- enemy die state의 update에서 현재 animation 상태를 체크한다 (GetCurrentAnimatorStateInfo) 
- 죽은 상태에서도 die 애니메이션이 실행되지 않는 버그를 수정하였다.

Feature enemy bug fix

---

Assets/Animations/ShakeMachine/Close.anim
Assets/Animations/ShakeMachine/Open.anim
Assets/Prefabs/ObjectInTrain/GearObj.prefab
Assets/Prefabs/ObjectInTrain/GearObj.prefab.meta
Assets/Prefabs/ObjectInTrain/ShakeMachine.prefab
Assets/Scripts/InteractionObjects/ShakeMachine.cs

- 흔들림 유지 장치 기어 추가 시 연출 추가
- 흔들림 수리 시 작은 기어 오브젝트가 위에서 아래로 떨어짐 
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/81548078/10fbf585-5f68-4918-89bf-f024e4581500

Feature shake object

---

Assets/Scripts/Player/PlayerAttack.cs

- 마우스 방향 공격
- 플레이어 공격시 입력 마우스 위치로 Ray를 쏴서 그 위치를 바라보도록 함
- 변경 전
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/667777f6-b760-4980-ac7f-a2e27c9bf7f1
- 변경 후
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/717ac26c-07a9-4a17-ba31-dd431775d4f2

Feature-UpdateAttack

---

Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/EnemyIdleState.cs
Assets/Scripts/Train/Train.cs

- 게임 시작 시 Enemy Path Erorr 해결 
- 오류가 나는 부분에 예외처리

:lock: ㅣ enemy Path Error 예외처리

---

Assets/Scenes/GameCycle.unity
Assets/Scripts/Managers/GameFlow/InGameManager.cs
Assets/Scripts/Train/NomalTrain.cs
Assets/Scripts/Train/StartTrain.cs
Assets/Scripts/Train/StoreTrain.cs

- 플레이어 움직임 변경
- 카메라와 기차의 각도를 변경

Feature-PlayerMoveDiagonal

---

Assets/Scripts/Managers/GameFlow/InGameManager.cs

Hotfix-TrainPosion

---

Assets/Prefabs/Camera/QuarterViewCam.prefab
Assets/Prefabs/Train/ModelTrain/BossTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StoreTrain_People .prefab
Assets/Scenes/GameCycle.unity
Assets/Scenes/ModelTestScene.unity

:art: | Camera 수정

---

Assets/Prefabs/ObjectInTrain/ShakeMachine.prefab
Assets/Prefabs/ObjectInTrain/TreasureBox.prefab
Assets/Prefabs/SpawnPoint/NomalTrainSpawnPoint1.prefab
Assets/Prefabs/SpawnPoint/NomalTrainSpawnPoint2.prefab

- 기차 요소 크기 수정
- 의자 크기 수정
- 보상상자 크기 수정

Hot fix chair scale

---

Assets/Scripts/InteractionObjects/Gear.cs
Assets/Scripts/InteractionObjects/TreasureBox.cs
Assets/Scripts/Managers/GameFlow/InGameManager.cs
Assets/Scripts/Managers/Gear/GearManager.cs

- 기어 리스트 삭제
- 기어 리스트 추가 제거 로직 삭제

:fire: l Gear system

---

Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab

Hotfix train door

---

Assets/Prefabs/Train/ModelTrain/BossTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StoreTrain_People .prefab

Hotfix-TrainFix

---

Assets/Scenes/GameCycle.unity

- 카메라 시점 변경
- 카메라 시점 orientation -> perspective

🎨 | 카메라 시점 변경

---

Assets/Animations/Enemy/Boss/Boss_Cave.controller
Assets/Animations/Enemy/Boss/cave_Boss_2@Idle.fbx.meta
Assets/Materials/Enemy/Boss.meta
Assets/Materials/Enemy/Boss/metal.003.mat
Assets/Materials/Enemy/Boss/metal.003.mat.meta
Assets/Materials/Enemy/Boss/wood.003.mat
Assets/Materials/Enemy/Boss/wood.003.mat.meta
Assets/Materials/Enemy/Boss/wood.004.mat
Assets/Materials/Enemy/Boss/wood.004.mat.meta
Assets/Scripts/Enemy/Controller/EnemyController_Boss_Cave.cs
Assets/Scripts/Managers/Shake/ShakeManager.cs

- Boss Attack 
- 보스의 위엄을 살린 공격 변경

Feature boss attack

---

Assets/Prefabs/Enemy/TempEnemy_Bomb.prefab
Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Prefabs/Enemy/TempEnemy_Range.prefab
Assets/Prefabs/Enemy/TempEnemy_Scientist.prefab

- 몬스터 서클
- 몬스터 아래 서클 추가
- 몬스터 스케일 조정

Feature enemy circle

---

Assets/Prefabs/Enemy/Boss/Enemy_BossCave.prefab

- Boss 크기 조절 
- 기존 0.8 에서 0.5로 사이즈 변경

boss scale set

---

Assets/Animations/Enemy/Melee/Enemy_Melee.controller
Assets/Animations/Enemy/Melee/Enemy_Melee@Idle@Reacting.fbx.meta
Assets/Animations/Enemy/Range/Enemy_Range.overrideController
Assets/Animations/Enemy/Range/Enemy_Range@Idle@Reacting.fbx.meta
Assets/Animations/Enemy/Scientist/Enemy_Scientist.controller
Assets/Animations/Enemy/Scientist/Scientist@Idle@Reacting.fbx.meta
Assets/Prefabs/Enemy/TempEnemy_Bomb.prefab
Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Prefabs/Enemy/TempEnemy_Range.prefab
Assets/Prefabs/Enemy/TempEnemy_Scientist.prefab
Assets/Prefabs/Enemy/UI/HPCanvas.prefab
Assets/Scripts/Enemy/Controller/EnemyController_Melee.cs
Assets/Scripts/Enemy/Controller/EnemyController_Range.cs
Assets/Scripts/Enemy/Controller/EnemyController_Scientist.cs
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/EnemyAttackState.cs
Assets/Scripts/Enemy/State/EnemyAttackWalkState.cs
Assets/Scripts/Enemy/State/EnemyDieState.cs
Assets/Scripts/Enemy/State/EnemyDiscoveryState.cs
Assets/Scripts/Enemy/State/EnemyDiscoveryState.cs.meta
Assets/Scripts/Enemy/State/EnemyHitState.cs
Assets/Scripts/Enemy/State/EnemyIdleState.cs
Assets/Scripts/Enemy/State/EnemyMoveState.cs
Assets/Scripts/Enemy/UI/EnemyUI.cs

- 몬스터 감지 이벤트 
- 몬스터 플레이어 발견 시 느낌표 표시 
- 몬스터 플레이어 발견 시 애니메이션 재생
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80678083/450e05e4-b3c2-45d5-843f-9afceb2c0fde

Feature exclamation mark

---

Assets/Prefabs/Train/ModelTrain/BossTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/DoorCol.prefab
Assets/Prefabs/Train/ModelTrain/DoorCol.prefab.meta
Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StoreTrain_People .prefab
Assets/Prefabs/Train/ModelTrain/Wall.prefab
Assets/Prefabs/Train/ModelTrain/Wall.prefab.meta

- 기차 벽뚫 에러 해결
- 기차 프리팹 콜라이더 추가

:bug: ㅣ Train Prefab

---

Assets/Scripts/Enemy/Controller/EnemyController_Bomb.cs
Assets/Scripts/Enemy/Controller/EnemyController_Melee.cs
Assets/Scripts/Enemy/Controller/EnemyController_Range.cs
Assets/Scripts/Enemy/Controller/EnemyController_Scientist.cs

- Enemy State 초기화 
- 각 controller에 EnemyDiscoveryState 초기화 코드 추가

:bug: ㅣ enemy state 초기화

---

Assets/Prefabs/Train/ModelTrain/BossTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/FrontCol.prefab
Assets/Prefabs/Train/ModelTrain/FrontCol.prefab.meta
Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StoreTrain_People .prefab

:bug: ㅣ train collider

---

Assets/Prefabs/Train/ModelTrain/BossTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StoreTrain_People .prefab
Assets/Scripts/Player/PlayerAttack.cs
ProjectSettings/TagManager.asset

- 플레이어 공격 Raycast 버그 수정
- 벽에 layer 추가해서 플레이어 공격에 제외

:bug: | PlayerAttack Raycast Bug Fix

---

Assets/Scripts/Managers/GameFlow/InGameManager.cs

- 이전 기차가 사라지지 않게
- 다음 기차로 가도 기차가 사라지지 않게 함
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80678083/4bc0177c-63bd-4ef1-bf68-adb90fe50285

:sparkles: | 이전 기차가 사라지지 않게

---

Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Scenes/GameCycle.unity
Assets/Scripts/Player/PlayerController.cs

- 플레이어 스폰포인트 버그 수정
- GameCycle 씬 플레이어 위치 변경

:art: | 플레이어 씬 위치 변경

---

Assets/Scripts/Enemy/Controller/EnemyController_Bomb.cs
Assets/Scripts/Enemy/EnemyController.cs

- 폭탄 공격이 맞지 않는 버그 수정
- 공격범위 체크 부등호 수정

:art: | 공격범위 부등호 수정

---

Assets/Scripts/Player/PlayerAttack.cs

- 공격 Layer 체크 버그 
- LayerMask  변수 초기화

:bug: | LayerMask 변수 초기화

---

Assets/Scripts/Enemy/EnemyController.cs

- Enemy Destroy Logic Change
- 기존 죽음 처리 시  (스크립트가 컴포넌트로 존재하는) 몬스터 모델이 삭제 되었다 
- 이를 모델 오브젝트의 상위객체인 몬스터 객체를 삭제하게 변경 
- Destroy 함수를 호출할때 부모의 오브젝트를 파라미터로 넣었다.

:art: ㅣ enemy destroy Logic change

---

Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Scenes/GameCycle.unity
Assets/Scripts/Managers/GameFlow/InGameManager.cs
Assets/Scripts/Train/BossTrain.cs

- InGameManager Train Spawn Logic Change
- 인덱스를 이용하여 보스와 상점 칸의 프리팹 호출 
- InGameManager  오브젝트의 하이라이키 창에 나타나 있는 변수 수치 조정으로 칸 갯수를 조정할 수 있음 
- 보스 호출 또한 변수 호출로 매번 로직 수정 X

:art: ㅣ Boss and Store Train Spawn Logic Change

---

Assets/Animations/Player/LowPolyHumanAnimator.controller
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Resources/Prefabs/Item/GreatSwrod.prefab
Assets/Scripts/Item/Weapon/Dagger.cs
Assets/Scripts/Player/PlayerAttack.cs
Assets/Scripts/Player/PlayerController.cs
Assets/Scripts/Player/PlayerManager.cs
Assets/Scripts/Player/PlayerSkill.cs

- 무기 스킬 여러 번 나가는 버그 
- PlayerState가 Skill State로 변경되지 않는 버그 수정

Feature great sword skill bug

---

Assets/Animations/Enemy/Melee/Enemy_Melee.controller
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/EnemyDieState.cs
Assets/Scripts/State/State.cs

- 몬스터 안 죽는 버그 수정 
- 대검 스킬 공격시 몬스터가 안 죽는 버그를 수정하였다. 
- 기존 trigger를 사용하여 hit 와 die animation 둘다 처리 ( hit 상태일 때 die 가 제대로 호출되지 않음 ) 
- 그래서 animation substatemachie으로 hit trigger 발생시 hp가 0 이라면 die animation 호출 ( dieTrue 라는 bool 파라미터 사용)

Hotfix enemy die

---

Assets/Animations/Enemy/Melee/Enemy_Melee.controller
Assets/Animations/Enemy/Scientist/Enemy_Scientist.controller

- 엘리트 몬스터 죽음 처리 
- 기존 몬스터 죽음 처리 변경으로 인한 엘리트 몬스터 에니메이션 컨트롤러 변경

Hotfix scientist enemy die

---

Assets/Prefabs/Effect/GreatSwordSkillEffect.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Scripts/Item/Weapon/GreatSword.cs

- 대검 스킬 이펙트 삭제
- 1.5초 뒤에 대검 스킬 이펙트 삭제

:bug: | 대검 스킬 이펙트 삭제

---

Assets/Scripts/Enemy/State/EnemyDieState.cs

- 몬스터가 죽었을 때 통과
- 몬스터 죽었을 때 Collider 비활성화

:art: | 몬스터 죽었을 때 Collider 비활성화

---

Assets/Animations/Enemy/Melee/Enemy_Melee.controller
Assets/Animations/Enemy/Scientist/Enemy_Scientist.controller
Assets/Scripts/Player/PlayerHit.cs

- 플레이어 hit 중복 판정 수정
- 플레이어 hit가 중복 실행되는 상황 방지
- 변경 전
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/478227da-c1fd-48ec-98de-0439e91cb174
- 변경 후
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/c28d7f06-c74c-4395-a1c0-8e3594015de0

Feature player hit fix

---

Assets/Prefabs/SpawnPoint/NomalTrainSpawnPoint1.prefab
Assets/Prefabs/SpawnPoint/NomalTrainSpawnPoint2.prefab

- 의자 프리팹 모델 설정 
- 크기 30 30 30 -> 40 40 40 
- box 콜라이더 추가

:art: ㅣ 의자 모델 설정

---

Assets/Scripts/Player/PlayerAttack.cs
Assets/Scripts/Player/PlayerSkill.cs

- 스태미나가 마이너스로 가는 버그
- 임시 StaminaValue를 무기 별 스태미나 사용량으로 변경

:bug: | 임시 StaminaValue 변경

---

Assets/Prefabs/Train/ModelTrain/StoreTrain_People .prefab

- 상점 오브젝트 Collider가 없다
- 상점 오브젝트 BoxCollider 추가

:sparkles: | 상점 칸 Collider 추가

---

Assets/Prefabs/Enemy/TempEnemy_Bomb.prefab

- 대검으로 때렸을 때 Bomp가 안맞는 버그
- Bomp Enemty Collider Y Size 키움

:bug: | Bomb Enemty Collider Y Size 증가

---

Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Prefabs/Enemy/UI/HPCanvas.prefab

- 몬스터 Slider UI 개선
- Enemy Slider UI 변경

:art: | Enemy Slider UI 변경

---

Assets/Scenes/GameCycle.unity

- 스테이지 수 조정
- 스테이지 수 조정 (3스테이지 상점 6스테이지 보스)

:art: | 스테이지 수 조정

---

Assets/Scripts/Enemy/Controller/EnemyController_Bomb.cs
Assets/Scripts/Enemy/Controller/EnemyController_Boss_Cave.cs
Assets/Scripts/Enemy/Controller/EnemyController_Melee.cs
Assets/Scripts/Enemy/Controller/EnemyController_Range.cs
Assets/Scripts/Enemy/Controller/EnemyController_Scientist.cs
Assets/Scripts/Enemy/Data/EnemyData.cs
Assets/Scripts/Enemy/EnemyController.cs
Assets/Scripts/Enemy/State/Boss/BossEnemyAttackWalkState.cs
Assets/Scripts/Enemy/State/Boss/BossEnemyDieState.cs
Assets/Scripts/Enemy/State/Boss/BossEnemyIdleState.cs
Assets/Scripts/Enemy/State/Boss/BossEnemyMoveState.cs
Assets/Scripts/Enemy/State/EnemyAttackWalkState.cs
Assets/Scripts/Enemy/State/EnemyDieState.cs
Assets/Scripts/Enemy/State/EnemyDiscoveryState.cs
Assets/Scripts/Enemy/State/EnemyHitState.cs
Assets/Scripts/Enemy/State/EnemyIdleState.cs
Assets/Scripts/Enemy/State/EnemyMoveState.cs

- Animation parameter ID Hash value 캐싱
- Animator 파라미터를 string으로 호출하는 것을 모두 Hash value로 캐싱

:art: | Animation parameter ID Hash value 캐싱

---

Assets/Scripts/Managers/Shake/ShakeManager.cs

- 흔들림 수치 UI 버그
- 흔들림 수치가 최대치면 UI 업데이트를 하지 않게

:bug: | 흔들림 UI 고침

---

Assets/Scripts/Item/Weapon/GreatSword.cs
Assets/Scripts/Player/Player.cs

:bug: | _hp 최대치 제한

---

Assets/Scripts/Enemy/Controller/EnemyController_Bomb.cs

- 걸어다니는 폭탄 폭발 범위가 비정상적입니다
- 폭발 범위 조정 ( 5 -> 1.6f)

:art: | 폭탄 공격 사거리 조정

---

Assets/Resources/ScriptableObjects/Item/FistData.asset
Assets/Scripts/Player/PlayerAttack.cs
Assets/Scripts/Player/PlayerSkill.cs

- 주먹 사용 스태미나 추가
- 주먹 사용 시 스태미나 2 사용
- 잘못 된 변수 명 변경
- 변경 후
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/dde67d08-29f6-400f-b24c-41b970e34c12

:sparkles: | 주먹 사용 스태미나 추가

---

Assets/Prefabs/Camera/QuarterViewCam.prefab
Assets/Scenes/GameCycle.unity
Assets/Scripts/Managers/Shake/ShakeManager.cs

- 카메라 줌, 흔들림 디버프 누락
- 카메라에 빠진 스크립트 추가
- 흔들림에 누락된 코드 추가

Hotfix-MergeOmission

---

Assets/Resources/ScriptableObjects/Item/DaggerData.asset
Assets/Resources/ScriptableObjects/Item/GreatSwordData.asset
Assets/Resources/ScriptableObjects/Item/PotionData.asset
Assets/Scenes/GameCycle.unity
Assets/Scripts/Managers/GameFlow/InGameManager.cs
Assets/Scripts/UI/StartStageUI.cs

- 특수 스테이지 차별점
- 보스와 상점 스테이지 UI 텍스트 추가

:sparkles: | Boss, Store Stage UI Text

---

Assets/Scripts/Player/PlayerAttack.cs
Assets/Scripts/Player/PlayerRolling.cs
Assets/Scripts/Player/PlayerSkill.cs

- 스태미나 부족 텍스트 추가
- 공격, 스킬, 구르기 스태미나 부족 텍스트 추가
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/0a3632a0-fa13-4c10-8f3b-6584f0a33eb3

:sparkles: | 스태미나 부족 텍스트

---

Assets/Prefabs/ObjectInTrain/ShakeMachine.prefab
Assets/Prefabs/ObjectInTrain/TreasureBox.prefab
Assets/Prefabs/Train/ModelTrain/BossTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StoreTrain_People .prefab

-균형유지장치, 보상상자 위치 크기 조정
- 균형유지장치, 보상상자 위치 크기 조정

:art: | 균형유지장치, 보상상자 위치 크기 조정

---

Assets/Scenes/GameCycle.unity

- 상점 스테이지 위치 조정
- 3 -> 5 스테이지로 번경

:art: | 상점 스테이지 위치 조정

---

Assets/Scenes/TutorialScene.unity

- 플레이어 피격 시 효과 누락 버그 수정
- 플레이어에 hit volume의 참조가 빠져있는 누락 수정
- 문제 사항

Hotfix-TutorialSceneOmission

---

Assets/Prefabs/Manager/CursorManager.prefab
Assets/Prefabs/Manager/CursorManager.prefab.meta
Assets/Scenes/GameCycle.unity
Assets/Scenes/TitleScene.unity
Assets/Scripts/Inventory/InventoryManager.cs
Assets/Scripts/Managers/CursorManager.cs
Assets/Scripts/Managers/CursorManager.cs.meta
Assets/Scripts/Util/LoadSceneController.cs
Assets/Sprites/box.png.meta

- 마우스 커서 업그레이드
- 커서 이미지 변경
- 움직일 때 마우스 커서 회전
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80678083/5fbb09de-4bea-4958-a79d-8ccce4c7e7c3

🤩 | 마우스 커서 업그레이드

---

Assets/Scripts/Player/PlayerManager.cs

- 흔들림이 감소되도 어지러움 지속되는 버그 수정
- StopDizziness함수를 호출해서 어지러움을 멈춤
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82389915/4bd7efae-8e9a-4a00-9ef2-48a9efe202c6

흔들림이 감소되도 어지러움 지속되는 버그 수정

---

Assets/Scripts/Item/Weapon/Dagger.cs
Assets/Scripts/Item/Weapon/Fist.cs
Assets/Scripts/Item/Weapon/GreatSword.cs

- 플레이어 공격 버그 
- 플레이어가 공격 후 피격 시 hit animation으로 인해 공격 후처리가 누락 되던 오류 해결
- 변경 후
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/def0d549-f60c-4353-8883-407991992c9d

Fix-PlayerAttackDuplication

---

Assets/Scripts/Managers/CursorManager.cs
Assets/Scripts/Util/LoadSceneController.cs

- LoadSceneController Null 버그 수정
- LoadSceneController Null 버그 수정

:bug: | LoadSceneController Null 버그 수정

---

.github/workflows/activation.yml

- CI 스크립트 recycle
- CI 스크립트 recycle

🔀 :: CI 스크립트 Recycle

---

.github/workflows/activation.yml

🔀 :: 이름 변경

---

Assets/Scenes/GameCycle.unity

:sparkles: | 플레이어 옷 추가

---

Assets/Prefabs/SpawnPoint/NomalTrainSpawnPoint2.prefab

Feature-AdjustmentChairs

---

Assets/Prefabs/ObjectInTrain/ShakeMachine.prefab
Assets/Prefabs/Train/ModelTrain/BossTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StoreTrain_People .prefab

- 조명 빛 조정
- 흔들림 유지 장치 빛 제거
- 모든 기차 문쪽 랜턴 빛 추가

Feature adjustment lighting

---

Assets/Prefabs/Train/ModelTrain/BossTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StoreTrain_People .prefab

:sparkles: | 기차 벽 높이기

---

Assets/Materials/Enemy/Boss/metal.003.mat
Assets/Materials/TrainInside/Lamp/Right1.mat
Assets/Materials/TrainInside/Lamp/Right2.mat
Assets/Materials/Train_People/RightWall4.mat

- 오른쪽 벽 랜턴 투명화
- 기차 프리팹 오른쪽 벽 랜턴 투명

:art: | 오른쪽 벽 랜턴 투명화

---

Assets/Prefabs/Train/ModelTrain/BossTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/NormalTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People.prefab
Assets/Prefabs/Train/ModelTrain/StoreTrain_People .prefab
Assets/Scenes/GameCycle.unity

- 카메라가 벽을 뚫는 버그
- 기차 프리팹 벽에 Wall Layer 추가
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80678083/672aa21e-e0ff-48f5-ae0d-8a903065b72f

:art: | 기차 프리팹 벽에 Wall Layer 추가

---

Assets/Scripts/Enemy/Controller/EnemyController_Boss_Cave.cs

- 보스 공격 패턴 변경
- 기존 랜덤한 수치로 각 공격을 호출 -> 공격 패턴의 인덱스 (0,1,2)를 담은 배열의 요소를 순서대로 호출하게 변경

Boss Attack Pattern

---

Assets/Prefabs/Manager/ShakeManager.prefab
Assets/Scripts/Managers/Shake/ShakeManager.cs
Assets/Scripts/Player/PlayerManager.cs
Assets/Scripts/Shake/Shake.cs

- Crash 흔들림 추가
- 흔들림 수치 절반으로 줄이기
- Crash 흔들림 추가
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/5ce29358-15d8-4a00-828a-1a591dded713

Feature CrashShake

---

Assets/Animations/Enemy/Melee/Enemy_Melee_Die.fbx.meta
Assets/Resources/Prefabs/Item/Dagger.prefab
Assets/Resources/Prefabs/Item/GodGreatSwrod.prefab
Assets/Resources/Prefabs/Item/GreatSwrod.prefab

- 무기 Collider 크기 줄이기
- 단검, 대검 Collider 크기 줄이기
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80824477/67638743-3a23-42e7-ae50-33096ba733bd

Feature UpdateCollider

---

Assets/Scripts/Managers/Shake/ShakeManager.cs
Assets/Scripts/Shake/Shake.cs

- 흔들림 오버 버그 수정
- 흔들림 오버 시 발생 시 max 값에 초기화 버그 수정
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/810f09bf-f7b1-4019-bd55-30e5a4e44453

Hotfix-ShakeOver

---

Assets/Materials/Door/SpawnPoint/NomalTrainSpawnPoint1.prefab
Assets/Prefabs/SpawnPoint/NomalTrainSpawnPoint2.prefab

-  Train Spawn Point 
- 몬스터 스폰 포인트 재조정 
- 기존 위치가 너무 문쪽에 가까이 붙어 있어서 재조정

:art: ㅣspawn point postion

---

Assets/Prefabs/Enemy/EnemySpawnBomb.prefab
Assets/Scripts/Enemy/EnemySpawn/EnemySpawnBomb.cs
Assets/Scripts/Enemy/UI/EnemyUI.cs

- 미친 과학자가 설치하는 폭탄을 때려서 부술 수 있게 제작
- 폭탄에 Entity를 상속시켜 hit, die 함수 구현
- hp바 생성
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82389915/c99cb599-e024-4cc2-944a-d3ff7bee355f

🔀| 미친과학자 폭탄이 때려지도록 변경

---

Assets/Data/Enemy/Temp_Enemy_Bomb.asset
Assets/Scripts/Enemy/Controller/EnemyController_Bomb.cs

- 폭탄 터지는 로직 수정
- 폭탄 공격 범위 수정
- 폭탄 로직 수정
- 본래 충돌 감지 방식 -> Agent의 Collider가 닿았을 때 -> Physics.Overap을 사용하여 감지
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/c65f0c2e-7b62-40f3-ba5b-f8d629358a34

Fix-FollowingBomb

---

Assets/Prefabs/Effect/WeaponTrail.meta
Assets/Prefabs/Effect/WeaponTrail/DaggerTrailVFX.prefab
Assets/Prefabs/Effect/WeaponTrail/DaggerTrailVFX.prefab.meta
Assets/Prefabs/Effect/WeaponTrail/GreatSwordTrailVFX.prefab
Assets/Prefabs/Effect/WeaponTrail/GreatSwordTrailVFX.prefab.meta
Assets/Prefabs/Effect/WeaponTrail/MeleeAttackTrailVFX.prefab
Assets/Prefabs/Effect/WeaponTrail/MeleeAttackTrailVFX.prefab.meta
Assets/Prefabs/Enemy/TempEnemy_Melee.prefab
Assets/Prefabs/Item/Weapon/Fist.prefab
Assets/Resources/Prefabs/Item/Dagger.prefab
Assets/Resources/Prefabs/Item/GreatSwrod.prefab
Assets/Scripts/Enemy/Controller/EnemyController_Melee.cs
Assets/Scripts/Enemy/State/EnemyDieState.cs
Assets/Scripts/Enemy/State/EnemyHitState.cs
Assets/Scripts/Item/Weapon/Dagger.cs
Assets/Scripts/Item/Weapon/GreatSword.cs

- 무기 공격 트레일 이펙트 개선
- GreatSword, Dagger 트레일 파티클 제작
- Melee 몬스터 공격 트레일 파티클 제작
- Fist 주먹 TrailRenderer 값 조정
- GreatSword, Dagger, EnemyHitState 에서 TrailRenderer 대신 ParticleSystem 으로 변경
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80824477/821c0138-44bd-472b-b7ed-1ba7da320609

New Weapon Trail Effect

---

Assets/Resources/ScriptableObjects/Item/DaggerData.asset
Assets/Resources/ScriptableObjects/Item/GodSwordData.asset
Assets/Resources/ScriptableObjects/Item/GreatSwordData.asset

- 이펙트 추가
- 타격 이펙트 추가
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/fff4e912-b345-4882-949d-03224f3ed2ca

Feature-PlayerEffect

---

Assets/Prefabs/Train/ModelTrain/StartTrain_People_Test.prefab
Assets/Prefabs/Train/ModelTrain/StartTrain_People_Test.prefab.meta
Assets/Scenes/TestScene.unity
Assets/Scenes/TestScene.unity.meta
Assets/Scripts/TestScene.cs
Assets/Scripts/TestScene.cs.meta

- 테스트 씬 제작
- 기어 원하는 만큼 추가 가능
- 기차 건너뛰기 치트 제작
- TestScene 인스펙터에서 건너뛰기 키 설정 가능 (영상에서는 N)
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/80824477/f8339b79-7bac-4c29-be4f-9a9332674657

Feature test scene

---

Assets/Scenes/GameCycle.unity

- 기차를 통과하는 물체 삭제
- 광산 배경에 Background_3 요소에 있는 기둥을 삭제하였습니다.
- 문제가 되는 기둥 영상 ↓
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/7d292ee8-f23e-4041-b312-c60bbd5487fb

Hotfix-Background
